diff --git a/Makefile b/Makefile
index 55c8307..eb9bd78 100755
--- a/Makefile
+++ b/Makefile
@@ -4,8 +4,8 @@ HEADERS = $(wildcard kernel/*.h drivers/*.h)
 OBJ = ${C_SOURCES:.c=.o}
 
 # Change this if your cross-compiler is somewhere else
-CC = /usr/bin/gcc
-GDB = /usr/bin/gdb
+CC = gcc
+GDB = gdb
 # -g: Use debugging symbols in gcc
 CFLAGS = -g -m32 -fno-pie -ffreestanding
 
@@ -16,11 +16,11 @@ os-image.bin: boot/bootsect.bin kernel.bin
 # '--oformat binary' deletes all symbols as a collateral, so we don't need
 # to 'strip' them manually on this case
 kernel.bin: boot/kernel_entry.o ${OBJ}
-	/usr/bin/ld -m elf_i386 -o $@ -Ttext 0x1000 $^ --oformat binary
+	ld -m elf_i386 -o $@ -Ttext 0x1000 $^ --oformat binary
 
 # Used for debugging purposes
 kernel.elf: boot/kernel_entry.o ${OBJ}
-	/usr/bin/ld -m elf_i386 -o $@ -Ttext 0x1000 $^ 
+	ld -m elf_i386 -o $@ -Ttext 0x1000 $^ 
 
 run: os-image.bin
 	qemu-system-i386 -vga std -drive file=$<,index=0,if=floppy,format=raw
